consul:
  agent_addr: 127.0.0.1:8500
  service_name: nusadua-test

log:
  access_log_level: debug
  access_log_path: ./log/access.log

  app_log_path: ./log/app.log
  app_log_level: debug

  stat_log_path: ./log/stat.log
  stat_log_level: debug

rpc:
  host: 127.0.0.1
  port: 1989

router:
  # Interval(ms) to get node info from consul
  refresh_interval: 1000
  replica: 3
