// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
	"net"
	"net/url"
	"nusadua/rpc"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  void create_task(string name, i64 max_key)")
	fmt.Fprintln(os.Stderr, "  void multi_push( keys,  values)")
	fmt.Fprintln(os.Stderr, "   multi_pull( keys)")
	fmt.Fprintln(os.Stderr, "  void range_push(i64 start_key, i64 end_key,  values)")
	fmt.Fprintln(os.Stderr, "   range_pull(i64 start_key, i64 end_key)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = math.MinInt32 // will become unneeded eventually
	_ = strconv.Atoi
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := rpc.NewParameterServerClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "create_task":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "CreateTask requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1, err31 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err31 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.CreateTask(value0, value1))
		fmt.Print("\n")
		break
	case "multi_push":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "MultiPush requires 2 args")
			flag.Usage()
		}
		arg32 := flag.Arg(1)
		mbTrans33 := thrift.NewTMemoryBufferLen(len(arg32))
		defer mbTrans33.Close()
		_, err34 := mbTrans33.WriteString(arg32)
		if err34 != nil {
			Usage()
			return
		}
		factory35 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt36 := factory35.GetProtocol(mbTrans33)
		containerStruct0 := rpc.NewMultiPushArgs()
		err37 := containerStruct0.ReadField1(jsProt36)
		if err37 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.Keys
		value0 := argvalue0
		arg38 := flag.Arg(2)
		mbTrans39 := thrift.NewTMemoryBufferLen(len(arg38))
		defer mbTrans39.Close()
		_, err40 := mbTrans39.WriteString(arg38)
		if err40 != nil {
			Usage()
			return
		}
		factory41 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt42 := factory41.GetProtocol(mbTrans39)
		containerStruct1 := rpc.NewMultiPushArgs()
		err43 := containerStruct1.ReadField2(jsProt42)
		if err43 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.Values
		value1 := argvalue1
		fmt.Print(client.MultiPush(value0, value1))
		fmt.Print("\n")
		break
	case "multi_pull":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MultiPull requires 1 args")
			flag.Usage()
		}
		arg44 := flag.Arg(1)
		mbTrans45 := thrift.NewTMemoryBufferLen(len(arg44))
		defer mbTrans45.Close()
		_, err46 := mbTrans45.WriteString(arg44)
		if err46 != nil {
			Usage()
			return
		}
		factory47 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt48 := factory47.GetProtocol(mbTrans45)
		containerStruct0 := rpc.NewMultiPullArgs()
		err49 := containerStruct0.ReadField1(jsProt48)
		if err49 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.Keys
		value0 := argvalue0
		fmt.Print(client.MultiPull(value0))
		fmt.Print("\n")
		break
	case "range_push":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "RangePush requires 3 args")
			flag.Usage()
		}
		argvalue0, err50 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err50 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err51 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err51 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		arg52 := flag.Arg(3)
		mbTrans53 := thrift.NewTMemoryBufferLen(len(arg52))
		defer mbTrans53.Close()
		_, err54 := mbTrans53.WriteString(arg52)
		if err54 != nil {
			Usage()
			return
		}
		factory55 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt56 := factory55.GetProtocol(mbTrans53)
		containerStruct2 := rpc.NewRangePushArgs()
		err57 := containerStruct2.ReadField3(jsProt56)
		if err57 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Values
		value2 := argvalue2
		fmt.Print(client.RangePush(value0, value1, value2))
		fmt.Print("\n")
		break
	case "range_pull":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "RangePull requires 2 args")
			flag.Usage()
		}
		argvalue0, err58 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err58 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err59 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err59 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.RangePull(value0, value1))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
